# **Info for the spot robot to build description from this yaml** #
# If a URDF is available, use cca_spot_urdf.yaml instead.
# Define the reference frame, joint axes, their locations, and the tool's position.
# Add or remove joint fields as needed to accurately represent the robot.
ref_frame:
  - name: # Example: arm0_base_link

robot_joints:
  - name: # Example: arm0_shoulder_roll 
    w: # Example: [0, 0, 1]
    q: # Example: [0, 0, 0]

  - name: 
    w: 
    q: 

  - name: 
    w: 
    q: 

  - name: 
    w: 
    q: 

  - name: 
    w: 
    q: 

  - name: 
    w: 
    q: 

end_effector:
  - gripper_joint_name: 
    frame_name: # This will be the parent frame for the tool
    q: 

tool:
  - name: # This is usually at the center of the palm
    offset_from_ee_frame: # Tool location from EE frame
