####################################################################################
# ROS-related attributes pertaining to Spot for visualization of joint trajectories#
####################################################################################

/**: # to enable parameter usage across different nodes
  ros__parameters:

    joint_states_topic: "/spot_driver/joint_states" # Joint states topic name

    planning_group: "arm" # MoveIt planning group name

    ref_frame: "arm0_base_link" # Default frame where the CCA planning plugin will show the screw interactive marker

    ee_frame: "arm0_fingers" # End-effector frame

    tool_frame: "cca_tool_frame" # Frame that follows the screw path for planning purposes

    ee_to_tool_offset: [0.07805, 0.0008, -0.01772] # Location of the tool in the EE frame

    rviz_fixed_frame: "base_footprint" # Base frame from the urdf
