# **Info for the spot robot to build description from URDF** #
# Provide the reference frame, kinematic chain, end effector and tool info.
ref_frame:
  - name: base_footprint # Example: base_link

kinematic_chain:
  - base_joint_name: body_x # Example: joint_1
    end_joint_name: arm0_wrist_roll # Example: joint_6

end_effector:
  - frame_name: arm0_tool0 # Example: ee_link
    gripper_joint_name: arm0_fingers # Example: joint_6 # Unused but provide one valid joint name

tool: # This does not have to be in the URDF, and is usually located at the center of the palm.
  - name: arm0_tool0 # Example: robot_tool 
    offset_from_ee_frame: [0.0, 0.0, 0.0] # Example: [0.0, 0.0, 0.02] # Tool location in the EE frame
